package pri.weiqiang.daojapanese;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LESSON_TITLE".
 */
public class lesson_title {

    private String lesson;
    private String lesson_title;

    public lesson_title() {
    }

    public lesson_title(String lesson, String lesson_title) {
        this.lesson = lesson;
        this.lesson_title = lesson_title;
    }

    public String getLesson() {
        return lesson;
    }

    public void setLesson(String lesson) {
        this.lesson = lesson;
    }

    public String getLesson_title() {
        return lesson_title;
    }

    public void setLesson_title(String lesson_title) {
        this.lesson_title = lesson_title;
    }

}
