package pri.weiqiang.daojapanese;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LESSONS".
 */
public class lessons {

    private Long id;
    private String book;
    private String title;
    private String count;

    public lessons() {
    }

    public lessons(Long id) {
        this.id = id;
    }

    public lessons(Long id, String book, String title, String count) {
        this.id = id;
        this.book = book;
        this.title = title;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBook() {
        return book;
    }

    public void setBook(String book) {
        this.book = book;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

}
