package pri.weiqiang.daojapanese;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WORDS".
 */
public class words {

    private Long id;
    /** Not-null value. */
    private String book_id;
    private String lesson_id;
    private String word;
    private String phonetic;
    private String translation;
    private Integer fav;
    private Integer cache;

    public words() {
    }

    public words(Long id) {
        this.id = id;
    }

    public words(Long id, String book_id, String lesson_id, String word, String phonetic, String translation, Integer fav, Integer cache) {
        this.id = id;
        this.book_id = book_id;
        this.lesson_id = lesson_id;
        this.word = word;
        this.phonetic = phonetic;
        this.translation = translation;
        this.fav = fav;
        this.cache = cache;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBook_id() {
        return book_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBook_id(String book_id) {
        this.book_id = book_id;
    }

    public String getLesson_id() {
        return lesson_id;
    }

    public void setLesson_id(String lesson_id) {
        this.lesson_id = lesson_id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getPhonetic() {
        return phonetic;
    }

    public void setPhonetic(String phonetic) {
        this.phonetic = phonetic;
    }

    public String getTranslation() {
        return translation;
    }

    public void setTranslation(String translation) {
        this.translation = translation;
    }

    public Integer getFav() {
        return fav;
    }

    public void setFav(Integer fav) {
        this.fav = fav;
    }

    public Integer getCache() {
        return cache;
    }

    public void setCache(Integer cache) {
        this.cache = cache;
    }

}
